In [1]:
import jqdatasdk as jq
jq.auth('13848214153','4157399AABBcc!')

auth success 


In [18]:
from datetime import date
s = date.fromisoformat('2022-04-30')
e = date.fromisoformat('2022-05-02')
a = jq.get_trade_days(start_date=s,end_date=e)
print(a.size - 1)

-1


In [20]:
e

datetime.date(2022, 5, 2)

In [ ]:
jq.get_trade_days(start_date='2022-01-01', end_date='2022-04-29')

In [18]:
len(jq.get_all_trade_days())

4693

In [20]:
import rqdatac as rq

In [ ]:
rq.init()

In [4]:
import time
from datetime import datetime,timedelta
def get_fundamentals_info(stock):
    q = jq.query(jq.valuation.turnover_ratio,
                jq.valuation.market_cap,
                jq.indicator.eps
                ).filter(jq.valuation.code.in_([stock]))
    current_dt = time.strftime("%Y-%m-%d", time.localtime())
    current_dt = datetime.strptime(current_dt, '%Y-%m-%d')
    previous_date  = current_dt - timedelta(days = 1)
    df = jq.get_fundamentals_continuously(q, end_date = previous_date, count = 5, panel = False)
    print(df)

In [5]:
get_fundamentals_info('600989.XSHG')

          day         code  turnover_ratio  market_cap     eps
0  2022-04-22  600989.XSHG          0.9998   1044.2705  0.2381
1  2022-04-25  600989.XSHG          2.3330    947.4701  0.2381
2  2022-04-26  600989.XSHG          2.0911    891.7366  0.2381
3  2022-04-27  600989.XSHG          2.8844    981.2036  0.2381
4  2022-04-28  600989.XSHG          2.1139    992.9369  0.2381


In [6]:
%%time

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [7]:
get_fundamentals_info('600989.XSHG')

          day         code  turnover_ratio  market_cap     eps
0  2022-04-22  600989.XSHG          0.9998   1044.2705  0.2381
1  2022-04-25  600989.XSHG          2.3330    947.4701  0.2381
2  2022-04-26  600989.XSHG          2.0911    891.7366  0.2381
3  2022-04-27  600989.XSHG          2.8844    981.2036  0.2381
4  2022-04-28  600989.XSHG          2.1139    992.9369  0.2381


In [10]:
import numpy as np
a = np.log(np.array([1,2]))

In [11]:
a

array([0.        , 0.69314718])

In [37]:
from stock_spider.spider import stock_histroy_info

In [38]:
current_dt = time.strftime("%Y-%m-%d", time.localtime())
current_dt = datetime.strptime(current_dt, '%Y-%m-%d')
previous_date  = current_dt - timedelta(days = 1)
previous_date = datetime.strftime(previous_date,"%Y-%m-%d")
data = stock_histroy_info('0.159915',str(previous_date.replace('-','')),limit=30)['klines']

In [39]:
result = []
for d in data:
    result.append(tuple(d.split(',')))

In [40]:
import pandas as pd
#result.insert(0,('date','open','close','high','low'))
df = pd.DataFrame(result)
df.rename(columns={0:'date',1:'open',2:'close',3:'high',4:'low'},inplace=True)
df = df.set_index('date')

In [41]:
df = df[1:].astype('float32')


In [42]:
df

open  close   high    low           5             6
date                                                            
2022-03-21  2.639  2.636  2.666  2.614   4590040.0  1.212819e+09
2022-03-22  2.623  2.602  2.626  2.589   3043426.0  7.928708e+08
2022-03-23  2.619  2.629  2.639  2.597   3441752.0  9.022776e+08
2022-03-24  2.605  2.620  2.638  2.571   4342960.0  1.128841e+09
2022-03-25  2.612  2.565  2.627  2.559   5088554.0  1.313442e+09
2022-03-28  2.540  2.512  2.545  2.494   5459154.0  1.374742e+09
2022-03-29  2.517  2.511  2.548  2.499   4138832.0  1.044201e+09
2022-03-30  2.527  2.610  2.610  2.524   5443448.0  1.401462e+09
2022-03-31  2.595  2.574  2.600  2.563   3904354.0  1.006760e+09
2022-04-01  2.550  2.580  2.599  2.548   4210102.0  1.086474e+09
2022-04-06  2.566  2.550  2.577  2.533   3535043.0  9.004870e+08
2022-04-07  2.535  2.496  2.547  2.495   4428186.0  1.112917e+09
2022-04-08  2.496  2.491  2.525  2.467   3466390.0  8.641130e+08
2022-04-11  2.460  2.386  2.465  2.378   6050103.0  1.456177e+09
2022-04-12  2.386  2.440  2.442  2.381   4713928.0  1.136473e+09
2022-04-13  2.418  2.394  2.433  2.391   4781737.0  1.152802e+09
2022-04-14  2.420  2.389  2.430  2.365   7573057.0  1.810301e+09
2022-04-15  2.360  2.385  2.406  2.339   5226941.0  1.238914e+09
2022-04-18  2.361  2.412  2.413  2.335   5381764.0  1.280921e+09
2022-04-19  2.398  2.377  2.430  2.368   4388862.0  1.049973e+09
2022-04-20  2.376  2.288  2.376  2.284   8180802.0  1.899263e+09
2022-04-21  2.270  2.240  2.304  2.227   6554452.0  1.485233e+09
2022-04-22  2.221  2.225  2.252  2.207   5942086.0  1.324393e+09
2022-04-25  2.177  2.103  2.192  2.103  10441595.0  2.241222e+09
2022-04-26  2.103  2.086  2.150  2.083  10201517.0  2.151858e+09
2022-04-27  2.066  2.200  2.200  2.057  13651751.0  2.893832e+09
2022-04-28  2.172  2.158  2.194  2.138   7788323.0  1.683688e+09
2022-04-29  2.166  2.244  2.250  2.152   8381799.0  1.849314e+09
2022-05-05  2.200  2.212  2.244  2.174   7654924.0  1.693007e+09

In [43]:
y = df['log'] = np.log(df.close)

In [59]:
aaa = df.close
aaa = list(aaa)

In [74]:
close_price = [float('%.3f' % x) for x in list(df.close)]

In [76]:
close_price.append(30)
np.log(close_price[-30:])

array([0.95628038, 0.96660355, 0.96317432, 0.94195848, 0.92107925,
       0.92068108, 0.95935022, 0.94546111, 0.9477894 , 0.93609336,
       0.91468945, 0.91268424, 0.86961832, 0.89199804, 0.87296561,
       0.87087487, 0.86919912, 0.88045628, 0.86583919, 0.82767807,
       0.80647587, 0.79975692, 0.7433649 , 0.73524836, 0.78845736,
       0.76918187, 0.80825999, 0.79389708, 3.40119738, 3.40119738])

In [91]:
x = df['num'] = np.arange(df.log.size)

In [92]:
slope, intercept = np.polyfit(x, y, 1)
#print(np.poly1d(np.polyfit(y,x,deg=1)))

In [93]:
import math
annualized_returns = math.pow(math.exp(slope), 250) - 1

In [94]:
annualized_returns

-0.5669701655382637

In [95]:
r_squared = 1 - (sum( (y - (slope * x + intercept)) **2) / ((len(y) - 1) * np.var(y, ddof=1)))

# 计算方式见：https://zh.wikipedia.org/wiki/%E5%86%B3%E5%AE%9A%E7%B3%BB%E6%95%B0
# R^2 = 1-SSres/SStot
# y平均 = (1/y.size) * sum(y)
# 于是可以得到总平方和：SStot = sum((y - (1/y.size) * sum(y)) ** 2)
# 残差平方和 : SSres = sum( (y - (slope*x + intercept) ** 2))
# r^2 = 1 - (SSres / SStot )


In [96]:
score = annualized_returns * r_squared

In [97]:
score

-0.3607548173648432

In [101]:
len(jq.get_index_stocks('000300.XSHG'))

300

In [103]:
current_dt = time.strftime("%Y-%m-%d", time.localtime())
type(current_dt)

str

In [4]:
a = jq.alpha191.alpha_002('000001.XSHE','2022-04-25',fq ='pre')
a

000001.XSHE    1.546992
dtype: float64

In [23]:
import numpy as np

In [26]:
res = np.random.random(30)

In [29]:
res

array([0.99884447, 0.67958418, 0.88828231, 0.04354752, 0.57668751,
       0.80139849, 0.71613653, 0.631153  , 0.14471442, 0.17480676,
       0.78181867, 0.46074292, 0.63703769, 0.44361304, 0.82883275,
       0.87573151, 0.97453183, 0.10606381, 0.96502572, 0.37627687,
       0.16455061, 0.25596103, 0.4561716 , 0.65338959, 0.45361525,
       0.95517673, 0.47690019, 0.99547094, 0.24527365, 0.20973726])

In [30]:
res = res.reshape((1,30,1))

In [31]:
res

array([[[0.99884447],
        [0.67958418],
        [0.88828231],
        [0.04354752],
        [0.57668751],
        [0.80139849],
        [0.71613653],
        [0.631153  ],
        [0.14471442],
        [0.17480676],
        [0.78181867],
        [0.46074292],
        [0.63703769],
        [0.44361304],
        [0.82883275],
        [0.87573151],
        [0.97453183],
        [0.10606381],
        [0.96502572],
        [0.37627687],
        [0.16455061],
        [0.25596103],
        [0.4561716 ],
        [0.65338959],
        [0.45361525],
        [0.95517673],
        [0.47690019],
        [0.99547094],
        [0.24527365],
        [0.20973726]]])

In [ ]:
# 函数新增代码
def predict(history,code):
    base_url = "http://49.233.19.128:8080/index/"
    post_data = {
        "history_list":history,
        "stock_code":code 
    }
    res = requests.post("http://49.233.19.128:8080/index/",data=post_data)
    d = json.loads(res.content.decode())
    return float(d["predict_value"])


close_price = [float('%.3f' % float(x)) for x in list(data.close)]
pre_value = predict(close_price,stock)
close_price.append(pre_value)
close_price = close_price[-30:]
print("今日预测值：{}".format(pre_value))